module.exports = {
  "GeomertyTEC": [
    {
      "type": "autogenerated",
      "dirName": "."
    },
    {
      "type": "link",
      "label": "GitHub",
      "href": "https://github.com/ProyectosCE/CE1106_T01"
    },
    {
      "type": "link",
      "label": "Azure DevOps",
      "href": "https://dev.azure.com/Tareas-CE1106/Tarea%201%20-%20CE1106"
    }
  ]
};